version: "3"
services:
  db:
    image: "postgres"
    container_name: "coc_postgres"
    environment:
      - POSTGRES_USER=coc
      - POSTGRES_PASSWORD = pwd123
      - POSTGRS_DB = coc
    ports:
      - "54320:5432"