definitions:
  Committee:
    type: object
    required:
      - name
      - description
      - totalSlots
    properties:
      name:
        type: string
      description:
        type: string
      totalSlots:
        type: integer
        format: int64
        minimum: 1
        example: 1
  CommitteeId:
    type: object
    required:
      - committeeId
      - name
      - description
      - totalSlots
    properties:
      committeeId:
        type: integer
        format: int64
        minimum: 1
        example: 1
      name:
        type: string
      description:
        type: string
      totalSlots:
        type: integer
        format: int64
        minimum: 1
        example: 1
  CommitteeAssignment:
    type: object
    required:
      - email
      - committeeId
      - startDate
      - endDate
    properties:
      email:
        type: string
      committeeId:
        type: integer
        minimum: 1
        example: 1
      startDate:
        type: string
        format: date
      endDate:
        type: string
        format: date
  CommitteeSlots:
    type: object
    required:
      - committeeId
      - senateDivision
      - slotRequirements
    properties:
      committeeId:
        type: integer
        minimum: 1
        example: 1
      senateDivision:
        type: integer
        minimum: 1
        example: 1
      slotRequirements:
        type: integer
        minimum: 1
        example: 1
tags:
  - name: 'committees'
    description: 'Everything about committees'
