definitions:
  Committee:
    type: object
    required:
      - name
      - description
      - totalSlots
    properties:
      name:
        type: string
      description:
        type: string
      totalSlots:
        type: integer
        format: int64
        minimum: 1
        example: 1
  CommitteeId:
    type: object
    required:
      - committeeId
      - name
      - description
      - totalSlots
    properties:
      committeeId:
        type: integer
        format: int64
        minimum: 1
        example: 1
      name:
        type: string
      description:
        type: string
      totalSlots:
        type: integer
        format: int64
        minimum: 1
        example: 1
  CommitteeAssignment:
    type: object
    required:
      - email
      - committeeId
      - startDate
      - endDate
    properties:
      email:
        type: string
      committeeId:
        type: integer
        minimum: 1
        example: 1
      startDate:
        type: string
        format: date
      endDate:
        type: string
        format: date
  CommitteeSlots:
    type: object
    required:
      - committeeId
      - senateDivision
      - slotRequirements
    properties:
      committeeId:
        type: integer
        minimum: 1
        example: 1
      senateDivision:
        type: integer
        minimum: 1
        example: 1
      slotRequirements:
        type: integer
        minimum: 1
        example: 1
  DepartmentAssociations:
    type: object
    requied:
      - email
      - departmentId
    properties:
      email:
        type: string
      departmentId:
        type: integer
        minimum: 1
        example: 1
  DepartmentAssociationsPut:
    type: object
    requied:
      - email
      - oldDepartmentId
      - newDepartmentId
    properties:
      email:
        type: string
      oldDepartmentId:
        type: integer
        minimum: 1
        example: 1
      newDepartmentId:
        type: integer
        minimum: 1
        example: 2
  SurveyChoice:
    type: object
    requied:
      - choiceId
      - surveyDate
      - email
      - committeeId
    properties:
      choiceId:
        type: integer
        example: 1
      surveyDate:
        type: integer
        example: 2020
      email:
        type: string
      committeeId:
        type: integer
        example: 1
  SurveyData:
    type: object
    required:
      - surveyDate
      - email
      - isInterested
      - expertise
    properties:
      surveyDate:
        type: integer
        example: 2020
      email:
        type: string
      isInterested:
        type: boolean
      expertise:
        type: string
responses:
  Committee:
    type: object
    properties:
      committee_id:
        type: integer
        format: int64
        example: 1
      name:
        type: string
      description:
        type: string
      total_slots:
        type: integer
        format: int64
        example: 1
  CommitteeAssignment:
    type: array
    items:
      type: object
      properties:
        email:
          type: string
        committee_id:
          type: integer
          format: int64
          example: 1
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
  CommitteeInfo:
    type: object
    properties:
      name:
        type: string
      id:
        type: integer
        format: int64
        example: 1
      description:
        type: string
      totalSlots:
        type: integer
        format: int64
        example: 1
      slotsRemaining:
        type: integer
        format: int64
        example: 1
      committeeSlots:
        type: array
        items:
          type: object
          properties:
            senateShortname:
              type: string
            slotFilled:
              type: integer
            slotMinimum:
              type: integer
            slotsRemaining:
              type: integer
  CommitteeSlotsCommittee:
    type: array
    items:
      type: object
      properties:
        senate_division_short_name:
          type: string
        slot_requirements:
          type: integer
  CommitteeSlotsSenateDivision:
    type: array
    items:
      type: object
      properties:
        committee_id:
          type: integer
          format: int64
          example: 1
        slot_requirements:
          type: integer
  Committees:
    type: array
    items:
      type: object
      properties:
        committee_id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
        description:
          type: string
        total_slots:
          type: integer
          format: int64
          example: 1
  Department:
    type: object
    properties:
      department_id:
        type: integer
        format: int64
        example: 1
      name:
        type: string
      description:
        type: string
  Departments:
    type: array
    items:
      type: object
      properties:
        department_id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
        description:
          type: string
  DepartmentAssociations:
    type: array
    items:
      type: object
      properties:
        email:
          type: string
        department_id:
          type: integer
          format: int64
          example: 1
  Reports:
    type: object
    properties:
      total_slots:
        type: integer
        format: int64
        example: 200
      slots_filled:
        type: integer
        format: int64
        example: 150
      senate_division:
        type: array
        items:
          type: object
          properties:
            senate_division:
              type: string
            slotFilled:
              type: integer
              example: 10
            slotMinimum:
              type: integer
              example: 12
            slotsRemaining:
              type: integer
              example: 2
  SenateDivision:
    type: object
    properties:
      senate_division_short_name:
        type: string
      name:
        type: string
  SenateDivisions:
    type: array
    items:
      type: object
      properties:
        senate_division_short_name:
          type: string
        name:
          type: string
  SurveyChoice:
    type: array
    items:
      type: object
      properties:
        choice_id:
          type: integer
          example: 1
        survey_date:
          type: integer
          example: 2020
        email:
          type: string
        committee_id:
          type: integer
          example: 1
  SurveyData:
    type: object
    properties:
      surveyDate:
        type: integer
        example: 2020
      email:
        type: string
      isInterested:
        type: boolean
      expertise:
        type: string

tags:
  - name: 'committee'
    description: 'Everything about committee'
  - name: 'committee-assignment'
    description: 'Everything about committee-assignments'
  - name: 'committee-slots'
    description: 'Everything about committee-slots'
  - name: 'committees'
    description: 'Everything about committees'
  - name: 'department'
    description: 'Everything about a department'
  - name: 'department-associations'
    description: 'Everything about a department-association'
  - name: 'departments'
    description: 'Everything about departments'
  - name: 'reports'
    description: 'Everything about reports'
  - name: 'senate-division'
    description: 'Everything about a senate division'
  - name: 'senate-divisions'
    description: 'Everything about senate divisions'
  - name: 'survey-choice'
    description: 'Everything about survey-choice'
  - name: 'survey-data'
    description: 'Everything about survey-data'
